import express from 'express'
import * as authMiddleware from '../middleware/auth.middleware.js'
import * as leadsController from '../controllers/leads.controller.js'

const router = express.Router()

// Kanban boards (manual board column management; automated board is read-only —
// its columns are generated by the Tune Agent instruction flow)
router.get('/:chatbotId/kanban', authMiddleware.authenticateToken, leadsController.getBoards)
router.post(
  '/:chatbotId/kanban/columns',
  authMiddleware.authenticateToken,
  leadsController.createColumn
)
router.patch(
  '/:chatbotId/kanban/columns/reorder',
  authMiddleware.authenticateToken,
  leadsController.reorderColumns
)
router.patch(
  '/:chatbotId/kanban/columns/:columnId',
  authMiddleware.authenticateToken,
  leadsController.renameColumn
)
router.delete(
  '/:chatbotId/kanban/columns/:columnId',
  authMiddleware.authenticateToken,
  leadsController.deleteColumn
)

// Leads
router.get('/:chatbotId/leads', authMiddleware.authenticateToken, leadsController.getLeads)
router.post('/:chatbotId/leads', authMiddleware.authenticateToken, leadsController.createLead)
router.patch(
  '/:chatbotId/leads/:leadId/move',
  authMiddleware.authenticateToken,
  leadsController.moveLead
)
router.patch(
  '/:chatbotId/leads/:leadId',
  authMiddleware.authenticateToken,
  leadsController.updateLead
)
router.delete(
  '/:chatbotId/leads/:leadId',
  authMiddleware.authenticateToken,
  leadsController.deleteLead
)

export default router
