export interface TuneQuestion {
  q: string
  placeholder: string
}

/** Hard cap on interview length — mirrors MAX_TUNE_QUESTIONS on the backend. */
export const MAX_TUNE_QUESTIONS = 8

/**
 * The fixed opening question of the AI interview. Follow-up questions are
 * generated by the backend based on the answers so far.
 */
export const FIRST_TUNE_QUESTION: TuneQuestion = {
  q: 'What is your app or business for, and what is its main theme?',
  placeholder:
    'e.g. A SaaS project-management tool for remote teams — we want the bot to answer product questions and qualify trial signups into sales leads.',
}

/** Seeded fallback questions, used only when AI question generation fails. */
export const TUNE_QUESTIONS: TuneQuestion[] = [
  {
    q: 'What should we call your agent, and what is its core role?',
    placeholder: 'e.g. Atlas — a research assistant that summarizes long product docs for PMs.',
  },
  {
    q: 'Who is the primary user, and what problem are they solving?',
    placeholder:
      'e.g. Internal product team trying to triage customer feedback into themes each week.',
  },
  {
    q: 'What tone and personality should the agent embody?',
    placeholder: 'e.g. Warm but concise. Avoids jargon. Uses plain language and short sentences.',
  },
  {
    q: 'What capabilities must your agent absolutely have?',
    placeholder:
      'e.g. Search internal docs, summarize tickets, draft customer-facing replies, cite sources.',
  },
  {
    q: 'Are there any topics, actions, or behaviors the agent must avoid?',
    placeholder: 'e.g. Never discuss pricing, never share competitor info, never speculate on roadmap.',
  },
  {
    q: 'Share one example of an ideal exchange.',
    placeholder:
      'e.g. User: "What\'s blocking checkout?"  Agent: "Top 3 themes — payment retries (42%), address validation (28%), 3DS prompts (18%)."',
  },
  {
    q: 'What domain knowledge or context should be loaded by default?',
    placeholder: 'e.g. Latest changelog, brand voice doc, pricing sheet, last 30 days of support tickets.',
  },
]

/** Prompt section headings, parallel to TUNE_QUESTIONS. */
const PROMPT_SECTIONS = [
  'Identity & Role',
  'Target User',
  'Tone & Personality',
  'Capabilities',
  'Guardrails',
  'Example Exchange',
  'Knowledge Base',
]

export interface TuneAnswer {
  q: string
  a: string
}

/** Compile collected answers into a structured markdown system prompt. */
export function buildPrompt(answers: TuneAnswer[], modelLabel: string): string[] {
  const lines: string[] = []
  lines.push(`# System Prompt · ${modelLabel}`)
  lines.push('')
  answers.forEach((row, i) => {
    lines.push(`## ${PROMPT_SECTIONS[i] || 'Additional Context'}`)
    lines.push(row.a)
    lines.push('')
  })
  lines.push('## Output style')
  lines.push('Respond with clear, structured Markdown. Cite sources when relevant.')
  return lines
}
